CREATE TABLE IF NOT EXISTS user(
	id BIGINT NOT NULL AUTO_INCREMENT,
	name VARCHAR(200) NOT NULL,
	phone VARCHAR(100) NOT NULL,
	email VARCHAR(200) NOT NULL,
	password VARCHAR(200) NOT NULL,
	rule VARCHAR(100) NOT NULL,
	date_registration DATE NOT NULL,
	
	PRIMARY KEY (id)
	
)