CREATE TABLE IF NOT EXISTS publishing_companies(
	id BIGINT NOT NULL AUTO_INCREMENT,
	name VARCHAR(200) NOT NULL,
	city VARCHAR(50) NOT NULL,
	state VARCHAR(5) NOT NULL,
	country VARCHAR(100) NOT NULL,
	
	PRIMARY KEY (id)
)
